INSERT INTO pages (slug, tenant_id, title, content, published_at) 
VALUES 
  ('home', 'tenant-local-dev', 'Strona główna', '{
    "elements": [
      {"id":"home_hero_title_0","type":"text","component":"HeroSection","value":"Inteligentne folie PDLC i LCD na okna","path":"props.title"},
      {"id":"home_hero_subtitle_1","type":"text","component":"HeroSection","value":"Prywatność na żądanie bez rolet — do domu, biura i hoteli.","path":"props.subtitle"},
      {"id":"home_hero_bg_2","type":"image","component":"HeroSection","value":"https://images.pexels.com/photos/1457842/pexels-photo-1457842.jpeg?auto=compress&cs=tinysrgb&w=1600","path":"props.bgImage"},
      {"id":"home_nav_logo_alt_3","type":"text","component":"Navbar","value":"Logo Inteligentne Folie","path":"logo.alt"},
      {"id":"home_features_title_4","type":"text","component":"Features","value":"Dlaczego inteligentne folie PDLC to przyszłość wnętrz?","path":"props.title"},
      {"id":"home_features_subtitle_5","type":"text","component":"Features","value":"Technologia PDLC i LCD pozwala w sekundę przełączyć szkło z matowego na przezroczyste. To prywatność, światło i nowoczesny design w jednej tafli.","path":"props.subtitle"},
      {"id":"home_cta_title_6","type":"text","component":"CTA","value":"Zamów darmową próbkę folii PDLC","path":"props.title"},
      {"id":"home_cta_subtitle_7","type":"text","component":"CTA","value":"Przekonaj się na własne oczy, jak działa technologia PDLC. Wysyłamy próbki za darmo w całej Polsce!","path":"props.subtitle"},
      {"id":"home_cta_button_text_8","type":"text","component":"CTA","value":"Zamów teraz bezpłatnie","path":"props.button.text"},
      {"id":"home_cta_button_href_9","type":"link","component":"CTA","value":"/kontakt","path":"props.button.href"},
      {"id":"home_products_title_10","type":"text","component":"Products","value":"Najchętniej wybierane folie inteligentne","path":"props.title"},
      {"id":"home_products_subtitle_11","type":"text","component":"Products","value":"Sprawdzone rozwiązania dla domu, biura i hoteli","path":"props.subtitle"},
      {"id":"home_products_item_12","type":"image","component":"Products","value":"https://images.pexels.com/photos/1457842/pexels-photo-1457842.jpeg?auto=compress&cs=tinysrgb&w=800","path":"products.0.image"},
      {"id":"home_products_item_13","type":"text","component":"Products","value":"Folia PDLC Samoprzylepna","path":"products.0.title"},
      {"id":"home_products_item_14","type":"text","component":"Products","value":"od 1200 zł/m²","path":"products.0.price"},
      {"id":"home_products_item_15","type":"text","component":"Products","value":"Opacjalność: 95-99% • ON: 80-92% • Czas przełączenia ~1 s","path":"products.0.specs"},
      {"id":"home_products_item_16","type":"text","component":"Products","value":"Łatwy montaż","path":"products.0.features.0"},
      {"id":"home_products_item_17","type":"text","component":"Products","value":"Bez laminacji","path":"products.0.features.1"},
      {"id":"home_products_item_18","type":"text","component":"Products","value":"Gotowa do użycia","path":"products.0.features.2"},
      {"id":"home_realizacje_title_19","type":"text","component":"Portfolio","value":"Nasze realizacje","path":"props.title"},
      {"id":"home_realizacje_subtitle_20","type":"text","component":"Portfolio","value":"Zobacz jak folia PDLC transformuje wnętrza w całej Polsce","path":"props.subtitle"},
      {"id":"home_realizacje_item_21","type":"image","component":"Portfolio","value":"https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=600","path":"projects.0.image"},
      {"id":"home_realizacje_item_22","type":"text","component":"Portfolio","value":"Apartament Warszawa","path":"projects.0.title"},
      {"id":"home_realizacje_item_23","type":"text","component":"Portfolio","value":"Łazienka z folią PDLC","path":"projects.0.category"},
      {"id":"home_faq_title_24","type":"text","component":"FAQ","value":"Najczęściej zadawane pytania","path":"props.title"},
      {"id":"home_faq_item_25","type":"text","component":"FAQ","value":"Jaka jest różnica między folią PDLC a LCD?","path":"faqs.0.question"},
      {"id":"home_faq_item_26","type":"text","component":"FAQ","value":"Folia PDLC to samoprzylepna folia montowana na istniejących szybach, natomiast folia LCD wymaga procesu laminacji w szkle. Folie LCD oferują wyższą przezroczystość (~90-92% vs ~80-92%) i są bardziej trwałe, idealne dla projektów premium.","path":"faqs.0.answer"},
      {"id":"home_blog_title_27","type":"text","component":"Blog","value":"Blog","path":"props.title"},
      {"id":"home_blog_subtitle_28","type":"text","component":"Blog","value":"Aktualności, porady i inspiracje ze świata folii inteligentnych","path":"props.subtitle"},
      {"id":"home_blog_post_29","type":"text","component":"Blog","value":"Jak działa folia PDLC? Kompletny przewodnik dla początkujących","path":"blogPosts.0.title"},
      {"id":"home_blog_post_30","type":"text","component":"Blog","value":"Odkryj technologię kryształów ciekłych w folii PDLC. Dowiedz się jak przełączanie między stanem matowym a przezroczystym działa w praktyce.","path":"blogPosts.0.excerpt"},
      {"id":"home_contact_title_31","type":"text","component":"Contact","value":"Skontaktuj się z nami","path":"props.title"},
      {"id":"home_contact_subtitle_32","type":"text","component":"Contact","value":"Masz pytania o folie inteligentne? Chcesz umówić pomiar lub otrzymać wycenę?","path":"props.subtitle"},
      {"id":"home_contact_phone_33","type":"text","component":"Contact","value":"+48 123 456 789","path":"contactInfo.0.items.0.value"},
      {"id":"home_contact_email_34","type":"text","component":"Contact","value":"kontakt@inteligentnefolie.pl","path":"contactInfo.1.items.0.value"},
      {"id":"home_footer_copy_35","type":"text","component":"Footer","value":"© 2026 Inteligentne Folie. Wszelkie prawa zastrzeżone."},
      {"id":"home_floatingchat_desc_36","type":"text","component":"FloatingChat","value":"Masz pytanie? Napisz do nas!"}
    ]
  }', now()),
  ('inteligentne-folie', 'tenant-local-dev', 'Inteligentne Folie', '{
    "elements": [
      {"id":"inteligentne-folie_hero_title_0","type":"text","component":"HeroSection","value":"Inteligentne Folie PDLC i LCD","path":"props.title"},
      {"id":"inteligentne-folie_hero_subtitle_1","type":"text","component":"HeroSection","value":"Kup folię PDLC i LCD. Samoprzylepna i do laminacji. Ceny od 950 zł/m². Darmowa wycena i montaż w całej Polsce.","path":"props.subtitle"},
      {"id":"inteligentne-folie_hero_button_primary_text_2","type":"text","component":"HeroSection","value":"Kontakt","path":"props.hero_button_primary.text"},
      {"id":"inteligentne-folie_hero_button_primary_href_3","type":"link","component":"HeroSection","value":"/kontakt","path":"props.hero_button_primary.href"},
      {"id":"inteligentne-folie_hero_button_secondary_text_4","type":"text","component":"HeroSection","value":"Zobacz produkty","path":"props.hero_button_secondary.text"},
      {"id":"inteligentne-folie_hero_button_secondary_href_5","type":"link","component":"HeroSection","value":"/inteligentne-folie","path":"props.hero_button_secondary.href"},
      {"id":"inteligentne-folie_filters_title_6","type":"text","component":"Filters","value":"Filtruj produkty","path":"props.title"},
      {"id":"inteligentne-folie_filters_select_typ_7","type":"text","component":"Filters","value":"Wszystkie","path":"select.typ.option.0"},
      {"id":"inteligentne-folie_filters_select_typ_8","type":"text","component":"Filters","value":"Samoprzylepna","path":"select.typ.option.1"},
      {"id":"inteligentne-folie_filters_select_typ_9","type":"text","component":"Filters","value":"Do laminacji","path":"select.typ.option.2"},
      {"id":"inteligentne-folie_products_grid_10","type":"image","component":"ProductsGrid","value":"https://images.pexels.com/photos/1457842/pexels-photo-1457842.jpeg?auto=compress&cs=tinysrgb&w=800","path":"products.0.image"},
      {"id":"inteligentne-folie_products_item_11","type":"text","component":"ProductsGrid","value":"Folia PDLC Samoprzylepna Premium","path":"products.0.title"},
      {"id":"inteligentne-folie_products_item_12","type":"text","component":"ProductsGrid","value":"1200","path":"products.0.price"},
      {"id":"inteligentne-folie_products_item_13","type":"text","component":"ProductsGrid","value":"Przeźroczystość: 80% • Blok UV: 99% • Gwarancja: 5 lat","path":"products.0.specs"},
      {"id":"inteligentne-folie_products_item_14","type":"text","component":"ProductsGrid","value":"Łatwy montaż DIY","path":"products.0.features.0"},
      {"id":"inteligentne-folie_products_item_15","type":"text","component":"ProductsGrid","value":"Bez wymiany szyby","path":"products.0.features.1"},
      {"id":"inteligentne-folie_products_item_16","type":"text","component":"ProductsGrid","value":"Gotowa do użycia","path":"products.0.features.2"},
      {"id":"inteligentne-folie_products_item_17","type":"text","component":"ProductsGrid","value":"Przeźroczystość 80%","path":"products.0.features.3"},
      {"id":"inteligentne-folie_products_item_18","type":"text","component":"ProductsGrid","value":"Folia LCD do Laminacji Ultra","path":"products.1.title"},
      {"id":"inteligentne-folie_products_item_19","type":"text","component":"ProductsGrid","value":"1500","path":"products.1.price"},
      {"id":"inteligentne-folie_products_item_20","type":"text","component":"ProductsGrid","value":"Przeźroczystość: 90% • Blok UV: 99% • Gwarancja: 10 lat","path":"products.1.specs"},
      {"id":"inteligentne-folie_products_item_21","type":"text","component":"ProductsGrid","value":"Najwyższa jakość","path":"products.1.features.0"},
      {"id":"inteligentne-folie_products_item_22","type":"text","component":"ProductsGrid","value":"Trwałość premium","path":"products.1.features.1"},
      {"id":"inteligentne-folie_products_item_23","type":"text","component":"ProductsGrid","value":"Najlepsza klarowność","path":"products.1.features.2"},
      {"id":"inteligentne-folie_products_item_24","type":"text","component":"ProductsGrid","value":"Przeźroczystość 90%","path":"products.1.features.3"},
      {"id":"inteligentne-folie_products_item_25","type":"text","component":"ProductsGrid","value":"Smart Glass System Kompletny","path":"products.2.title"},
      {"id":"inteligentne-folie_products_item_26","type":"text","component":"ProductsGrid","value":"2000","path":"products.2.price"},
      {"id":"inteligentne-folie_products_item_27","type":"text","component":"ProductsGrid","value":"Przeźroczystość: 85% • Sterowanie: WiFi • Gwarancja: 7 lat","path":"products.2.specs"},
      {"id":"inteligentne-folie_products_item_28","type":"text","component":"ProductsGrid","value":"Kompletny system","path":"products.2.features.0"},
      {"id":"inteligentne-folie_products_item_29","type":"text","component":"ProductsGrid","value":"Sterowanie WiFi","path":"products.2.features.1"},
      {"id":"inteligentne-folie_products_item_30","type":"text","component":"ProductsGrid","value":"Smart Home ready","path":"products.2.features.2"},
      {"id":"inteligentne-folie_products_item_31","type":"text","component":"ProductsGrid","value":"Przeźroczystość 85%","path":"products.2.features.3"},
      {"id":"inteligentne-folie_products_item_32","type":"text","component":"ProductsGrid","value":"Folia PDLC Biuro Standard","path":"products.3.title"},
      {"id":"inteligentne-folie_products_item_33","type":"text","component":"ProductsGrid","value":"1100","path":"products.3.price"},
      {"id":"inteligentne-folie_products_item_34","type":"text","component":"ProductsGrid","value":"Przeźroczystość: 80% • Blok UV: 95% • Gwarancja: 3 lata","path":"products.3.specs"},
      {"id":"inteligentne-folie_products_item_35","type":"text","component":"ProductsGrid","value":"Idealna do biur","path":"products.3.features.0"},
      {"id":"inteligentne-folie_products_item_36","type":"text","component":"ProductsGrid","value":"Łatwa instalacja","path":"products.3.features.1"},
      {"id":"inteligentne-folie_products_item_37","type":"text","component":"ProductsGrid","value":"Ekonomiczna","path":"products.3.features.2"},
      {"id":"inteligentne-folie_products_item_38","type":"text","component":"ProductsGrid","value":"Przeźroczystość 80%","path":"products.3.features.3"},
      {"id":"inteligentne-folie_products_item_39","type":"text","component":"ProductsGrid","value":"Folia PDLC Economy","path":"products.4.title"},
      {"id":"inteligentne-folie_products_item_40","type":"text","component":"ProductsGrid","value":"950","path":"products.4.price"},
      {"id":"inteligentne-folie_products_item_41","type":"text","component":"ProductsGrid","value":"Przeźroczystość: 75% • Blok UV: 90% • Gwarancja: 2 lata","path":"products.4.specs"},
      {"id":"inteligentne-folie_products_item_42","type":"text","component":"ProductsGrid","value":"Korzystna cena","path":"products.4.features.0"},
      {"id":"inteligentne-folie_products_item_43","type":"text","component":"ProductsGrid","value":"Dobry stosunek","path":"products.4.features.1"},
      {"id":"inteligentne-folie_products_item_44","type":"text","component":"ProductsGrid","value":"Łatwy montaż","path":"products.4.features.2"},
      {"id":"inteligentne-folie_products_item_45","type":"text","component":"ProductsGrid","value":"Przeźroczystość 75%","path":"products.4.features.3"},
      {"id":"inteligentne-folie_cta_title_46","type":"text","component":"CTA","value":"Zamów bezpłatną wycenę","path":"props.title"},
      {"id":"inteligentne-folie_cta_subtitle_47","type":"text","component":"CTA","value":"Podaj wymiary, wybierz rodzaj, a my wyślemy darmową wycenę. Możesz zamówić folię PDLC lub LCD, z montażem lub bez.","path":"props.subtitle"},
      {"id":"inteligentne-folie_comparison_title_48","type":"text","component":"ComparisonTable","value":"Porównanie: Folia samoprzylepna vs Folia do laminacji","path":"props.title"},
      {"id":"inteligentne-folie_help_title_49","type":"text","component":"HelpSection","value":"Potrzebujesz pomocy w wyborze?","path":"props.title"},
      {"id":"inteligentne-folie_help_subtitle_50","type":"text","component":"HelpSection","value":"Nasi eksperci pomogą Ci dobrać idealną folię inteligentną do Twoich potrzeb. Skontaktuj się z nami!","path":"props.subtitle"}
    ]
  }', now()),
  ('montaz-i-serwis', 'tenant-local-dev', 'Montaż i serwis', '{
    "elements": [
      {"id":"montaz-i-serwis_hero_title_0","type":"text","component":"HeroSection","value":"Montaż folii krok po kroku","path":"props.title"},
      {"id":"montaz-i-serwis_hero_subtitle_1","type":"text","component":"HeroSection","value":"Profesjonalny montaż folii PDLC i LCD w całej Polsce. Od konsultacji po serwis.","path":"props.subtitle"},
      {"id":"montaz-i-serwis_steps_title_2","type":"text","component":"StepsSection","value":"Proces montażu krok po kroku","path":"props.title"},
      {"id":"montaz-i-serwis_step_3_number_0","type":"text","component":"StepItem","value":"1","path":"steps.0.number"},
      {"id":"montaz-i-serwis_step_3_title_1","type":"text","component":"StepItem","value":"Konsultacja i pomiar","path":"steps.0.title"},
      {"id":"montaz-i-serwis_step_3_description_2","type":"text","component":"StepItem","value":"Bezpłatny projekt, pomiar, doradztwo techniczne i wycena szczegółowa","path":"steps.0.description"},
      {"id":"montaz-i-serwis_step_3_number_3","type":"text","component":"StepItem","value":"2","path":"steps.1.number"},
      {"id":"montaz-i-serwis_step_3_title_4","type":"text","component":"StepItem","value":"Przygotowanie powierzchni","path":"steps.1.title"},
      {"id":"montaz-i-serwis_step_3_description_5","type":"text","component":"StepItem","value":"Dokładne czyszczenie szyb, usuwanie zanieczyszczeń i przygotowanie do montażu","path":"steps.1.description"},
      {"id":"montaz-i-serwis_step_3_number_6","type":"text","component":"StepItem","value":"3","path":"steps.2.number"},
      {"id":"montaz-i-serwis_step_3_title_7","type":"text","component":"StepItem","value":"Montaż folii","path":"steps.2.title"},
      {"id":"montaz-i-serwis_step_3_description_8","type":"text","component":"StepItem","value":"Precyzyjne naklejanie lub laminacja folii przez doświadczony zespół","path":"steps.2.description"},
      {"id":"montaz-i-serwis_step_3_number_9","type":"text","component":"StepItem","value":"4","path":"steps.3.number"},
      {"id":"montaz-i-serwis_step_3_title_10","type":"text","component":"StepItem","value":"Podłączenie i konfiguracja","path":"steps.3.title"},
      {"id":"montaz-i-serwis_step_3_description_11","type":"text","component":"StepItem","value":"Instalacja sterownika, podłączenie elektryczne, konfiguracja smart home","path":"steps.3.description"},
      {"id":"montaz-i-serwis_step_3_number_12","type":"text","component":"StepItem","value":"5","path":"steps.4.number"},
      {"id":"montaz-i-serwis_step_3_title_13","type":"text","component":"StepItem","value":"Testy i instruktaż","path":"steps.4.title"},
      {"id":"montaz-i-serwis_step_3_description_14","type":"text","component":"StepItem","value":"Sprawdzenie działania, szkolenie z obsługi, przekazanie dokumentacji","path":"steps.4.description"},
      {"id":"montaz-i-serwis_benefits_title_15","type":"text","component":"BenefitsSection","value":"Dlaczego warto wybrać nasz montaż?","path":"props.title"},
      {"id":"montaz-i-serwis_benefits_item_16_icon_17","type":"text","component":"BenefitItem","value":"Users","path":"benefits.0.icon"},
      {"id":"montaz-i-serwis_benefits_item_16_title_18","type":"text","component":"BenefitItem","value":"Doświadczony zespół","path":"benefits.0.title"},
      {"id":"montaz-i-serwis_benefits_item_16_description_19","type":"text","component":"BenefitItem","value":"Ponad 10 lat doświadczenia. 500+ zrealizowanych projektów","path":"benefits.0.description"},
      {"id":"montaz-i-serwis_benefits_item_20_icon_21","type":"text","component":"BenefitItem","value":"Shield","path":"benefits.1.icon"},
      {"id":"montaz-i-serwis_benefits_item_20_title_22","type":"text","component":"BenefitItem","value":"10 lat gwarancji","path":"benefits.1.title"},
      {"id":"montaz-i-serwis_benefits_item_20_description_23","type":"text","component":"BenefitsItem","value":"Pełna gwarancja na produkt i montaż","path":"benefits.1.description"},
      {"id":"montaz-i-serwis_benefits_item_24_icon_25","type":"text","component":"BenefitItem","value":"Clock","path":"benefits.2.icon"},
      {"id":"montaz-i-serwis_benefits_item_24_title_26","type":"text","component":"BenefitItem","value":"Szybka realizacja","path":"benefits.2.title"},
      {"id":"montaz-i-serwis_benefits_item_24_description_27","type":"text","component":"BenefitItem","value":"Montaż standardowy w 1-2 dni robocze","path":"benefits.2.description"},
      {"id":"montaz-i-serwis_benefits_item_28_icon_29","type":"text","component":"BenefitItem","value":"MapPin","path":"benefits.3.icon"},
      {"id":"montaz-i-serwis_benefits_item_28_title_30","type":"text","component":"BenefitItem","value":"Cała Polska","path":"benefits.3.title"},
      {"id":"montaz-i-serwis_benefits_item_28_description_31","type":"text","component":"BenefitItem","value":"Montaż w całej Polsce, bez dodatkowych kosztów dojazdu","path":"benefits.3.description"},
      {"id":"montaz-i-serwis_cta_title_32","type":"text","component":"CTA","value":"Umów bezpłatny pomiar i wycenę","path":"props.title"},
      {"id":"montaz-i-serwis_cta_subtitle_33","type":"text","component":"CTA","value":"Nasi eksperci przyjadą do Ciebie, wykonają profesjonalny pomiar i przedstawią szczegółową wycenę","path":"props.subtitle"}
    ]
  }', now()),
  ('realizacje', 'tenant-local-dev', 'Realizacje', '{
    "elements": [
      {"id":"realizacje_hero_title_0","type":"text","component":"HeroSection","value":"Nasze realizacje","path":"props.title"},
      {"id":"realizacje_hero_subtitle_1","type":"text","component":"HeroSection","value":"Przesuń suwak aby zobaczyć efekt ON/OFF. Zobacz jak folia inteligentna transformuje wnętrza.","path":"props.subtitle"},
      {"id":"realizacje_projects_grid_2","type":"image","component":"ProjectsGrid","value":"https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=600","path":"projects.0.image"},
      {"id":"realizacje_projects_item_3","type":"text","component":"ProjectsGrid","value":"Apartament Warszawa","path":"projects.0.title"},
      {"id":"realizacje_projects_item_4","type":"text","component":"ProjectsGrid","value":"Łazienka z folią PDLC","path":"projects.0.category"},
      {"id":"realizacje_projects_item_5","type":"image","component":"ProjectsGrid","value":"https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?auto=compress&cs=tinysrgb&w=600","path":"projects.1.image"},
      {"id":"realizacje_projects_item_6","type":"text","component":"ProjectsGrid","value":"Biuro Kraków","path":"projects.1.title"},
      {"id":"realizacje_projects_item_7","type":"text","component":"ProjectsGrid","value":"Szkło konferencyjne","path":"projects.1.category"},
      {"id":"realizacje_projects_item_8","type":"image","component":"ProjectsGrid","value":"https://images.pexels.com/photos/1457842/pexels-photo-1457842.jpeg?auto=compress&cs=tinysrgb&w=600","path":"projects.2.image"},
      {"id":"realizacje_projects_item_9","type":"text","component":"ProjectsGrid","value":"Hotel Gdańsk","path":"projects.2.title"},
      {"id":"realizacje_projects_item_10","type":"text","component":"ProjectsGrid","value":"Szyby panoramiczne","path":"projects.2.category"},
      {"id":"realizacje_projects_item_11","type":"image","component":"ProjectsGrid","value":"https://images.pexels.com/photos/1454496/pexels-photo-1454496.jpeg?auto=compress&cs=tinysrgb&w=600","path":"projects.3.image"},
      {"id":"realizacje_projects_item_12","type":"text","component":"ProjectsGrid","value":"Rezydencja Wrocław","path":"projects.3.title"},
      {"id":"realizacje_projects_item_13","type":"text","component":"ProjectsGrid","value":"Drzwi szklane","path":"projects.3.category"},
      {"id":"realizacje_projects_item_14","type":"image","component":"ProjectsGrid","value":"https://images.pexels.com/photos/1454722/pexels-photo-1454722.jpeg?auto=compress&cs=tinysrgb&w=600","path":"projects.4.image"},
      {"id":"realizacje_projects_item_15","type":"text","component":"ProjectsGrid","value":"Showroom Poznań","path":"projects.4.title"},
      {"id":"realizacje_projects_item_16","type":"text","component":"ProjectsGrid","value":"Witryny sklepowe","path":"projects.4.category"},
      {"id":"realizacje_projects_item_17","type":"image","component":"ProjectsGrid","value":"https://images.pexels.com/photos/1571468/pexels-photo-1571468.jpeg?auto=compress&cs=tinysrgb&w=600","path":"projects.5.image"},
      {"id":"realizacje_projects_item_18","type":"text","component":"ProjectsGrid","value":"Klinika Łódź","path":"projects.5.title"},
      {"id":"realizacje_projects_item_19","type":"text","component":"ProjectsGrid","value":"Kabiny prysznicowe","path":"projects.5.category"},
      {"id":"realizacje_before_after_slider_20","type":"image","component":"BeforeAfterSlider","value":"https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=800","path":"beforeImage"},
      {"id":"realizacje_before_after_slider_21","type":"image","component":"BeforeAfterSlider","value":"https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?auto=compress&cs=tinysrgb&w=800","path":"afterImage"},
      {"id":"realizacje_before_after_slider_22","type":"text","component":"BeforeAfterSlider","value":"01","path":"stepNumber"},
      {"id":"realizacje_before_after_slider_23","type":"text","component":"BeforeAfterSlider","value":"Apartament Warszawa","path":"title"},
      {"id":"realizacje_before_after_slider_24","type":"text","component":"BeforeAfterSlider","value":"Łazienka z folią PDLC","path":"category"},
      {"id":"realizacje_cta_button_25","type":"text","component":"CTA","value":"Zobacz wszystkie realizacje","path":"props.text"},
      {"id":"realizacje_cta_href_26","type":"link","component":"CTA","value":"/realizacje","path":"props.href"}
    ]
  }', now()),
  ('blog', 'tenant-local-dev', 'Blog', '{
    "elements": [
      {"id":"blog_hero_title_0","type":"text","component":"HeroSection","value":"Blog","path":"props.title"},
      {"id":"blog_hero_subtitle_1","type":"text","component":"HeroSection","value":"Aktualności, porady i inspiracje ze świata folii inteligentnych","path":"props.subtitle"},
      {"id":"blog_posts_grid_2","type":"image","component":"PostsGrid","value":"https://images.pexels.com/photos/1457842/pexels-photo-1457842.jpeg?auto=compress&cs=tinysrgb&w=800","path":"blogPosts.0.image"},
      {"id":"blog_posts_item_3_title_4","type":"text","component":"PostCard","value":"Jak działa folia PDLC? Kompletny przewodnik dla początkujących","path":"blogPosts.0.title"},
      {"id":"blog_posts_item_3_excerpt_5","type":"text","component":"PostCard","value":"Odkryj technologię kryształów ciekłych w folii PDLC. Dowiedz się jak przełączanie między stanem matowym a przezroczystym działa w praktyce.","path":"blogPosts.0.excerpt"},
      {"id":"blog_posts_item_3_category_6","type":"text","component":"PostCard","value":"Poradnik","path":"blogPosts.0.category"},
      {"id":"blog_posts_item_3_author_7","type":"text","component":"PostCard","value":"Marek Kowalski","path":"blogPosts.0.author"},
      {"id":"blog_posts_item_3_date_8","type":"text","component":"PostCard","value":"15 grudnia 2024","path":"blogPosts.0.date"},
      {"id":"blog_posts_item_3_readtime_9","type":"text","component":"PostCard","value":"8 min","path":"blogPosts.0.readTime"},
      {"id":"blog_posts_item_4_image_10","type":"image","component":"PostCard","value":"https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?auto=compress&cs=tinysrgb&w=800","path":"blogPosts.1.image"},
      {"id":"blog_posts_item_4_title_11","type":"text","component":"PostCard","value":"Samodzielny montaż folii PDLC — czy to możliwe?","path":"blogPosts.1.title"},
      {"id":"blog_posts_item_4_excerpt_12","type":"text","component":"PostCard","value":"Porównanie montażu DIY vs profesjonalnego. Kiedy warto zrobić to samemu, a kiedy lepiej zatrudnić specjalistów?","path":"blogPosts.1.excerpt"},
      {"id":"blog_posts_item_4_author_13","type":"text","component":"PostCard","value":"Anna Nowak","path":"blogPosts.1.author"},
      {"id":"blog_posts_item_4_date_14","type":"text","component":"PostCard","value":"10 grudnia 2024","path":"blogPosts.1.date"},
      {"id":"blog_posts_item_4_readtime_15","type":"text","component":"PostCard","value":"6 min","path":"blogPosts.1.readTime"},
      {"id":"blog_posts_item_5_image_16","type":"image","component":"PostCard","value":"https://images.pexels.com/photos/1454722/pexels-photo-1454722.jpeg?auto=compress&cs=tinysrgb&w=800","path":"blogPosts.2.image"},
      {"id":"blog_posts_item_5_title_17","type":"text","component":"PostCard","value":"Folia PDLC vs rolety — co wybrać do biura?","path":"blogPosts.2.title"},
      {"id":"blog_posts_item_5_excerpt_18","type":"text","component":"PostCard","value":"Szczegółowe porównanie folii inteligentnych z tradycyjnymi roletami. Koszty, funkcjonalność, estetyka i wygoda użytkowania.","path":"blogPosts.2.excerpt"},
      {"id":"blog_posts_item_5_author_19","type":"text","component":"PostCard","value":"Marek Kowalski","path":"blogPosts.2.author"},
      {"id":"blog_posts_item_5_date_20","type":"text","component":"PostCard","value":"5 grudnia 2024","path":"blogPosts.2.date"},
      {"id":"blog_posts_item_5_readtime_21","type":"text","component":"PostCard","value":"10 min","path":"blogPosts.2.readTime"},
      {"id":"blog_posts_item_6_image_22","type":"image","component":"PostCard","value":"https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?auto=compress&cs=tinysrgb&w=800","path":"blogPosts.3.image"},
      {"id":"blog_posts_item_6_title_23","type":"text","component":"PostCard","value":"Integracja folii PDLC z systemem smart home","path":"blogPosts.3.title"},
      {"id":"blog_posts_item_6_excerpt_24","type":"text","component":"PostCard","value":"Jak podłączyć folię inteligentną do Google Home, Alexa lub własnego systemu automatyki? Praktyczny poradnik krok po kroku.","path":"blogPosts.3.excerpt"},
      {"id":"blog_posts_item_6_author_25","type":"text","component":"PostCard","value":"Piotr Wiśniewski","path":"blogPosts.3.author"},
      {"id":"blog_posts_item_6_date_26","type":"text","component":"PostCard","value":"28 listopada 2024","path":"blogPosts.3.date"},
      {"id":"blog_posts_item_6_readtime_27","type":"text","component":"PostCard","value":"12 min","path":"blogPosts.3.readTime"},
      {"id":"blog_posts_item_7_image_28","type":"image","component":"PostCard","value":"https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=800","path":"blogPosts.4.image"},
      {"id":"blog_posts_item_7_title_29","type":"text","component":"PostCard","value":"10 kreatywnych zastosowań folii PDLC w domu","path":"blogPosts.4.title"},
      {"id":"blog_posts_item_7_excerpt_30","type":"text","component":"PostCard","value":"Od sypialni po łazienkę — odkryj niekonwencjonalne sposoby wykorzystania folii inteligentnej w aranżacji wnętrz.","path":"blogPosts.4.excerpt"},
      {"id":"blog_posts_item_7_author_31","type":"text","component":"PostCard","value":"Anna Nowak","path":"blogPosts.4.author"},
      {"id":"blog_posts_item_7_date_32","type":"text","component":"PostCard","value":"20 listopada 2024","path":"blogPosts.4.date"},
      {"id":"blog_posts_item_7_readtime_33","type":"text","component":"PostCard","value":"7 min","path":"blogPosts.4.readTime"},
      {"id":"blog_posts_item_8_image_34","type":"image","component":"PostCard","value":"https://images.pexels.com/photos/271624/pexels-photo-271624.jpeg?auto=compress&cs=tinysrgb&w=800","path":"blogPosts.5.image"},
      {"id":"blog_posts_item_8_title_35","type":"text","component":"PostCard","value":"Żywotność folii PDLC — ile lat posłuży?","path":"blogPosts.5.title"},
      {"id":"blog_posts_item_8_excerpt_36","type":"text","component":"PostCard","value":"Czynniki wpływające na trwałość folii inteligentnej. Jak przedłużyć życie instalacji i na co uważać przy użytkowaniu?","path":"blogPosts.5.excerpt"},
      {"id":"blog_posts_item_8_author_37","type":"text","component":"PostCard","value":"Marek Kowalski","path":"blogPosts.5.author"},
      {"id":"blog_posts_item_8_date_38","type":"text","component":"PostCard","value":"15 listopada 2024","path":"blogPosts.5.date"},
      {"id":"blog_posts_item_8_readtime_39","type":"text","component":"PostCard","value":"5 min","path":"blogPosts.5.readTime"},
      {"id":"blog_cta_title_40","type":"text","component":"CTA","value":"Chcesz być na bieżąco?","path":"props.title"},
      {"id":"blog_cta_subtitle_41","type":"text","component":"CTA","value":"Zapisz się do newslettera i otrzymuj najnowsze artykuły oraz porady prosto na maila.","path":"props.subtitle"},
      {"id":"blog_newsletter_input_42","type":"text","component":"NewsletterInput","value":"Twój adres email","path":"props.placeholder"},
      {"id":"blog_newsletter_button_43","type":"text","component":"NewsletterButton","value":"Zapisz się","path":"props.text"},
      {"id":"blog_cta_additional_text_44","type":"text","component":"CTA","value":"Otrzymuj najnowsze artykuły oraz porady prosto na maila.","path":"props.extraText"}
    ]
  }', now()),
  ('kontakt', 'tenant-local-dev', 'Kontakt', '{
    "elements": [
      {"id":"kontakt_hero_title_0","type":"text","component":"HeroSection","value":"Skontaktuj się z nami","path":"props.title"},
      {"id":"kontakt_hero_subtitle_1","type":"text","component":"HeroSection","value":"Masz pytania o folie inteligentne? Chcesz umówić pomiar lub otrzymać wycenę?","path":"props.subtitle"},
      {"id":"kontakt_contact_info_title_2","type":"text","component":"ContactInfo","value":"Telefon","path":"contactInfo.0.title"},
      {"id":"kontakt_contact_info_item_3","type":"text","component":"ContactInfo","value":"+48 123 456 789","path":"contactInfo.0.items.0.value"},
      {"id":"kontakt_contact_info_item_4","type":"text","component":"ContactInfo","value":"+48 600 959 905","path":"contactInfo.0.items.1.value"},
      {"id":"kontakt_contact_info_item_5","type":"text","component":"ContactInfo","value":"Email","path":"contactInfo.1.title"},
      {"id":"kontakt_contact_info_item_6","type":"text","component":"ContactInfo","value":"kontakt@inteligentnefolie.pl","path":"contactInfo.1.items.0.value"},
      {"id":"kontakt_contact_info_item_7","type":"text","component":"ContactInfo","value":"wyceny@inteligentnefolie.pl","path":"contactInfo.1.items.1.value"},
      {"id":"kontakt_contact_info_item_8","type":"text","component":"ContactInfo","value":"Godziny pracy","path":"contactInfo.2.title"},
      {"id":"kontakt_contact_info_item_9","type":"text","component":"ContactInfo","value":"Pn-Pt","path":"contactInfo.2.items.0.value"},
      {"id":"kontakt_contact_info_item_10","type":"text","component":"ContactInfo","value":"Sob","path":"contactInfo.2.items.1.value"},
      {"id":"kontakt_locations_title_11","type":"text","component":"Locations","value":"Lokalizacje","path":"locations.title"},
      {"id":"kontakt_location_item_12_city_13","type":"text","component":"LocationItem","value":"Warszawa","path":"locations.0.city"},
      {"id":"kontakt_location_item_14_address_15","type":"text","component":"LocationItem","value":"ul. Marszałkowska 100","path":"locations.0.address"},
      {"id":"kontakt_location_item_16_phone_17","type":"text","component":"LocationItem","value":"+48 123 456 789","path":"locations.0.phone"},
      {"id":"kontakt_location_item_18_email_19","type":"text","component":"LocationItem","value":"warszawa@inteligentnefolie.pl","path":"locations.0.email"},
      {"id":"kontakt_location_item_20_hours_21","type":"text","component":"LocationItem","value":"Pn-Pt: 8:00-18:00","path":"locations.0.hours"},
      {"id":"kontakt_location_item_22_city_23","type":"text","component":"LocationItem","value":"Kraków","path":"locations.1.city"},
      {"id":"kontakt_location_item_24_address_25","type":"text","component":"LocationItem","value":"ul. Wielicka 28","path":"locations.1.address"},
      {"id":"kontakt_location_item_26_phone_27","type":"text","component":"LocationItem","value":"+48 123 456 790","path":"locations.1.phone"},
      {"id":"kontakt_location_item_28_email_29","type":"text","component":"LocationItem","value":"krakow@inteligentnefolie.pl","path":"locations.1.email"},
      {"id":"kontakt_location_item_30_hours_31","type":"text","component":"LocationItem","value":"Pn-Pt: 8:00-18:00","path":"locations.1.hours"},
      {"id":"kontakt_location_item_32_city_33","type":"text","component":"LocationItem","value":"Wrocław","path":"locations.2.city"},
      {"id":"kontakt_location_item_34_address_35","type":"text","component":"LocationItem","value":"ul. Świdnicka 38","path":"locations.2.address"},
      {"id":"kontakt_location_item_36_phone_37","type":"text","component":"LocationItem","value":"+48 123 456 791","path":"locations.2.phone"},
      {"id":"kontakt_location_item_38_email_39","type":"text","component":"LocationItem","value":"wroclaw@inteligentnefolie.pl","path":"locations.2.email"},
      {"id":"kontakt_location_item_40_hours_41","type":"text","component":"LocationItem","value":"Pn-Pt: 8:00-18:00","path":"locations.2.hours"},
      {"id":"kontakt_location_item_42_city_43","type":"text","component":"LocationItem","value":"Gdańsk","path":"locations.3.city"},
      {"id":"kontakt_location_item_44_address_45","type":"text","component":"LocationItem","value":"ul. Wałowa 20","path":"locations.3.address"},
      {"id":"kontakt_location_item_46_phone_47","type":"text","component":"LocationItem","value":"+48 123 456 792","path":"locations.3.phone"},
      {"id":"kontakt_location_item_48_email_49","type":"text","component":"LocationItem","value":"gdansk@inteligentnefolie.pl","path":"locations.3.email"},
      {"id":"kontakt_location_item_50_hours_51","type":"text","component":"LocationItem","value":"Pn-Pt: 8:00-18:00","path":"locations.3.hours"},
      {"id":"kontakt_form_title_52","type":"text","component":"ContactForm","value":"Wyślij wiadomość","path":"props.title"},
      {"id":"kontakt_form_subtitle_53","type":"text","component":"ContactForm","value":"Wypełnij formularz, a skontaktujemy się z Tobą w ciągu 24h.","path":"props.subtitle"},
      {"id":"kontakt_form_name_54","type":"text","component":"ContactForm","value":"Imię i nazwisko *","path":"formData.name"},
      {"id":"kontakt_form_phone_55","type":"text","component":"ContactForm","value":"Telefon","path":"formLabels.phone"},
      {"id":"kontakt_form_email_56","type":"text","component":"ContactForm","value":"Email *","path":"formLabels.email"},
      {"id":"kontakt_form_subject_57","type":"text","component":"ContactForm","value":"Temat *","path":"formLabels.subject"},
      {"id":"kontakt_form_message_58","type":"text","component":"ContactForm","value":"Wiadomość *","path":"formLabels.message"},
      {"id":"kontakt_form_submit_59","type":"text","component":"ContactForm","value":"Wyślij wiadomość","path":"button.text"},
      {"id":"kontakt_form_cta_60","type":"text","component":"ContactForm","value":"Zadzwoń: +48 123 456 789","path":"link.text"},
      {"id":"kontakt_form_cta_href_61","type":"link","component":"ContactForm","value":"tel:+48123456789","path":"link.href"},
      {"id":"kontakt_form_success_message_62","type":"text","component":"ContactForm","value":"Wiadomość wysłana!","path":"submittedMessage.text"},
      {"id":"kontakt_form_success_heading_63","type":"text","component":"ContactForm","value":"Dziękujemy za kontakt. Odpowiemy najszybciej jak to możliwe.","path":"submittedMessage.heading"}
    ]
  }', now());

-- Verificación de elementos extraídos por página:
-- home: 37 elementos
-- inteligentne-folie: 51 elementos
-- montaz-i-serwis: 34 elementos
-- realizacje: 27 elementos
-- blog: 45 elementos
-- kontakt: 64 elementos